<a href="https://colab.research.google.com/github/devaminta/Final-Year-Project-Recommendation-Domain/blob/main/friend_recommendation_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from  sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import OneHotEncoder
from datetime import datetime

In [2]:
import os
import kagglehub
import glob

dataset_dir = kagglehub.dataset_download("arindamsahoo/social-media-users")

csv_files = glob.glob(os.path.join(dataset_dir, "**", "*.csv"), recursive=True)

if csv_files:
    print("CSV file path:", csv_files[0])
else:
    print("No CSV file found.")

Downloading from https://www.kaggle.com/api/v1/datasets/download/arindamsahoo/social-media-users?dataset_version_number=2...

100%|██████████| 2.89M/2.89M [00:00<00:00, 122MB/s]

Extracting files...
CSV file path: /root/.cache/kagglehub/datasets/arindamsahoo/social-media-users/versions/2/SocialMediaUsersDataset.csv

In [3]:
dataset = pd.read_csv('/root/.cache/kagglehub/datasets/arindamsahoo/social-media-users/versions/2/SocialMediaUsersDataset.csv')
dataset = dataset.head(10000)

In [4]:
dataset

,UserID,Name,Gender,DOB,Interests,City,Country
0,1,Jesse Lawhorn,Female,1958-10-15,"'Movies', 'Fashion', 'Fashion', 'Books'",Sibolga,Indonesia
1,2,Stacy Payne,Female,2004-07-21,"'Gaming', 'Finance and investments', 'Outdoor ...",Al Abyār,Libya
2,3,Katrina Nicewander,Female,2000-02-07,"'DIY and crafts', 'Music', 'Science', 'Fashion'",Wādī as Sīr,Jordan
3,4,Eric Yarbrough,Male,1985-04-14,"'Outdoor activities', 'Cars and automobiles'",Matera,Italy
4,5,Daniel Adkins,Female,1955-09-18,"'Politics', 'History'",Biruaca,Venezuela
...,...,...,...,...,...,...,...
9995,9996,Mary Waddell,Female,1999-09-25,"'Pets', 'Music', 'Pets', 'Fitness'",Bālugaon,India
9996,9997,Philip Mcmanus,Female,1991-05-26,"'Fitness', 'Sports', 'Finance and investments'...",Michelstadt,Germany
9997,9998,Christina Frandsen,Female,1957-09-25,"'Travel', 'Outdoor activities', 'Gaming', 'Car...",Ropar,India
9998,9999,Carrie Weber,Male,1954-05-20,"'Social causes and activism', 'Pets', 'Books',...",North Decatur,United States
9999,10000,Jeffrey Blackburn,Female,1974-09-12,'Gardening',Acilia-Castel Fusano-Ostia Antica,Italy

In [5]:
interests = dataset['Interests'].str.get_dummies(', ')  # One-hot encode interests
interests.fillna(0, inplace=True)  # Replace NaN values with 0

In [6]:
interests

,'Art','Beauty','Books','Business and entrepreneurship','Cars and automobiles','Cooking','DIY and crafts','Education and learning','Fashion','Finance and investments',...,'Outdoor activities','Parenting and family','Pets','Photography','Politics','Science','Social causes and activism','Sports','Technology','Travel'
0,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9996,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
9997,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
9998,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
import pandas as pd
import numpy as np
from datetime import datetime

# Convert DOB to datetime format
dob = pd.to_datetime(dataset['DOB'])

# Get the current date
current_date = pd.Timestamp(datetime.now())

# Calculate age in years (approximate by days)
dataset['Age'] = (current_date - dob).dt.days // 365

dataset

,UserID,Name,Gender,DOB,Interests,City,Country,Age
0,1,Jesse Lawhorn,Female,1958-10-15,"'Movies', 'Fashion', 'Fashion', 'Books'",Sibolga,Indonesia,66
1,2,Stacy Payne,Female,2004-07-21,"'Gaming', 'Finance and investments', 'Outdoor ...",Al Abyār,Libya,20
2,3,Katrina Nicewander,Female,2000-02-07,"'DIY and crafts', 'Music', 'Science', 'Fashion'",Wādī as Sīr,Jordan,25
3,4,Eric Yarbrough,Male,1985-04-14,"'Outdoor activities', 'Cars and automobiles'",Matera,Italy,39
4,5,Daniel Adkins,Female,1955-09-18,"'Politics', 'History'",Biruaca,Venezuela,69
...,...,...,...,...,...,...,...,...
9995,9996,Mary Waddell,Female,1999-09-25,"'Pets', 'Music', 'Pets', 'Fitness'",Bālugaon,India,25
9996,9997,Philip Mcmanus,Female,1991-05-26,"'Fitness', 'Sports', 'Finance and investments'...",Michelstadt,Germany,33
9997,9998,Christina Frandsen,Female,1957-09-25,"'Travel', 'Outdoor activities', 'Gaming', 'Car...",Ropar,India,67
9998,9999,Carrie Weber,Male,1954-05-20,"'Social causes and activism', 'Pets', 'Books',...",North Decatur,United States,70
9999,10000,Jeffrey Blackburn,Female,1974-09-12,'Gardening',Acilia-Castel Fusano-Ostia Antica,Italy,50

In [8]:
age = dataset[['Age']]

In [9]:
location = dataset[['City', 'Country']]
location_encoded = pd.get_dummies(location).astype(int)

In [10]:
location_encoded

,City_Aalen,City_Aarschot,City_Abadan,City_Abancay,City_Abano Terme,City_Abasolo,City_Abay,City_Abaza,City_Abbiategrasso,City_Abeokuta,...,Country_United States,Country_Uruguay,Country_Uzbekistan,Country_Vatican,Country_Venezuela,Country_Vietnam,Country_Western Sahara,Country_Yemen,Country_Zambia,Country_Zimbabwe
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
features = pd.concat([interests, age, location_encoded], axis=1)

In [12]:
similarity_matrix = cosine_similarity(features)
cosine_sim_df = pd.DataFrame(similarity_matrix, index=dataset['UserID'], columns=dataset['UserID'])

In [45]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors

encoded_features = pd.concat([interests, age, location_encoded], axis=1)

knn = NearestNeighbors(n_neighbors=10).fit(encoded_features)

def get_recommendations(UserID, similarity_df, dataset, encoded_features, top_n=5):
    user_index = similarity_df.columns.get_loc(UserID)
    user_vector = encoded_features.iloc[[user_index]]

    ix = knn.kneighbors(user_vector, return_distance=False)

    closest = similarity_df.columns[ix.flatten()]

    return pd.DataFrame(closest, columns=['UserID']).merge(dataset).head(top_n)

In [46]:
result = get_recommendations(1, cosine_sim_df, dataset, encoded_features, top_n=5)

In [47]:
result

,UserID,Name,Gender,DOB,Interests,City,Country,Age
0,1,Jesse Lawhorn,Female,1958-10-15,"'Movies', 'Fashion', 'Fashion', 'Books'",Sibolga,Indonesia,66
1,9560,Mara Gonzalez,Female,1958-04-28,'Fashion',Sungailiat,Indonesia,66
2,9498,Robert Shulda,Female,1958-08-23,'Movies',Flemingdon Park,Canada,66
3,6016,Edith Beggs,Female,1958-09-27,'Fashion',Bayāna,India,66
4,1490,Peter Alatorre,Male,1958-06-05,'Fashion',Arcot,India,66

In [33]:
user_id = 1
similar_users_indices = similarity_matrix[user_id - 1].argsort()[::-1]  # Sort indices in descending order
similar_users = similar_users_indices[1:6]

In [34]:
# Print the similar users
for similar_user_index in similar_users:
    print(f"Similar User ID: {similar_user_index + 1}")

Similar User ID: 9560
Similar User ID: 4497
Similar User ID: 6360
Similar User ID: 7227
Similar User ID: 1119

In [35]:
dataset[dataset['UserID'] == 1]

,UserID,Name,Gender,DOB,Interests,City,Country,Age
0,1,Jesse Lawhorn,Female,1958-10-15,"'Movies', 'Fashion', 'Fashion', 'Books'",Sibolga,Indonesia,66

In [36]:
dataset[dataset['UserID'] == 9560]

,UserID,Name,Gender,DOB,Interests,City,Country,Age
9559,9560,Mara Gonzalez,Female,1958-04-28,'Fashion',Sungailiat,Indonesia,66

In [ ]:
dataset[dataset['UserID'] == 6360]

,UserID,Name,Gender,DOB,Interests,City,Country,Age
6359,6360,Gary Almaraz,Female,1965-04-05,'Movies',Blitar,Indonesia,59

In [ ]:
dataset[dataset['UserID'] == 1119]

,UserID,Name,Gender,DOB,Interests,City,Country,Age
1118,1119,Lacie Eagle,Female,1956-08-10,"'Fashion', 'Books'",Tecomán,Mexico,68

In [ ]:
dataset[dataset['UserID'] == 8384]

,UserID,Name,Gender,DOB,Interests,City,Country,Age
8383,8384,Doreen Joslin,Female,1963-02-01,"'Nature', 'Movies'",Karanganom,Indonesia,62